### PR TITLE
dns addon: make networks consistent for DNS to work.

### PR DESCRIPTION
**Pull request by sundbp**
Before the cluster IP range was 10.244.0.0/16, i.e. what flannel cared
about, but the actual used range for everything was 10.100.0.0/16 on the
kubernetes side. This made at least the DNS addon malfunction, not sure
about what else.

With this change I can now see the DNS addon working correctly inside
the cluster.

### CODE REVIEW

**Comment by sundbp** [comment]
Also, forgot to say, added the required flags when starting kubelet to allow DNS to work.

**Comment by sundbp** [comment]
I misunderstood the networking model. Pls ignore.

**Comment by rimusz** [comment]
no problem

**Comment by sundbp** [comment]
There were a couple of good parts to it though:
src/fleet/kube-kubelet.service
src/k8s/skydns-rc.yaml

I believe those changes are "good". kubelet needs the DNS args passed, and
the liveness check was using the wrong name for kubernetes (that health
check has changed in the k8 repo btw).

**Comment by rimusz** [comment]
@sundbp thanks for the tip, will check these files out

**Pull request closed without merging**
